export enum COLORED_ICONS {
    DISCOVER = 'discover',
    DINER = 'diner',
    CONFETTI = 'confetti',
    VISA = 'visa',
    MASTERCARD = 'mastercard',
    DEBIT = 'debit',
    AMERICAN_EXPRESS = 'american_express',
    JCB = 'jcb',
    LAUNCH = 'launch',
    UNIONPAY = 'unionpay',
    GOOGLE = 'google',
    AWS_LIGHT ='aws-light',
    AWS_DARK = 'aws-dark',
    HUGGING_FACE = 'hugging-face',
    NVIDIA = 'nvidia',
    OPEN_MM_LABS = 'open-mm-labs',
    DATALOOP = 'dataloop',
}